### ISSUE TITLE
配置了日志没有任何日志输出

### ISSUE THREAD

**Issue by rickywu** [v2ray/v2ray-core#1542]
1) 你正在使用哪个版本的 V2Ray？（如果服务器和客户端使用了不同版本，请注明）
4.15.0

2) 你的使用场景是什么？比如使用 Chrome 通过 Socks/VMess 代理观看 YouTube 视频。
Chrome 通过 Socks

3) 你看到的不正常的现象是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
访问配置了日志，但没有任何输出

5) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

服务器端配置:

```javascript
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [{
    "port": 10080,
    "protocol": "vmess",
    "settings": {
      "clients": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  }]
}

```

服务器端通过docker运行
```
version: "3.5"
services:
  shadowsocks:
    image: v2ray/official
    container_name: v2ray_1
    restart: always
    ports:
      - "10080:10080"
    environment:
      - config=/etc/v2ray/config.json
    volumes:
      - "/data/v2ray/config.json:/etc/v2ray/config.json"
      - "/data/v2ray/log:/var/log/v2ray"
```

客户端配置:

```javascript
{
  "log" : {
    "access": "D:\\Program Files\\V2Ray\\access.log",
    "error": "D:\\Program Files\\V2Ray\\error.log",
    "loglevel": "warning"
  },    
  "inbounds": [{
    "port": 1070,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "udp": true
    }
  }],
  "outbounds": [{
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "97.64.24.190",
        "port": 10080,
        "users": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
      }]
    }
  },{
    "protocol": "freedom",
    "tag": "direct",
    "settings": {}
  }],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [{
      "type": "field",
      "ip": ["geoip:private"],
      "outboundTag": "direct"
    }]
  }
}
```

除了v2ray.com/core: V2Ray 4.15.0 started，服务器端和客户端都没有其他任何日志，浏览器使用SwitchyOmega访问超时
